version: 2

jobs:
  build_and_push_image:
    docker:
      - image: docker:20.10.14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Login to Docker Hub
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Build Docker image
          command: docker build -t ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest .
      - run:
          name: Push Docker image
          command: docker push ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:latest

workflows:
  version: 2
  build_and_push_docker_image:
    triggers:
      - schedule:
          cron: "0 18 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_and_push_image
